### ISSUE TITLE
[Under the hood] Standardize on "Adapter Integration Tests" GitHub workflow

### ISSUE THREAD

**Issue by dbeatty10** [dbt-labs/dbt-postgres#181] opened 2024-12-11 16:28 UTC
### Is this your first time submitting a feature request?

- [X] I have read the [expectations for open source contributors](https://docs.getdbt.com/docs/contributing/oss-expectations)
- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing dbt-postgres functionality, rather than a Big Idea better suited to a discussion

#### Current

The adapter integration for most adapters maintained by dbt Labs can be found here:

https://github.com/dbt-labs/dbt-postgres/actions/workflows/integration.yml

But the ones for `dbt-postgres` are here instead:

https://github.com/dbt-labs/dbt-postgres/actions/workflows/integration-tests.yml

The difference is a file name of `integration-tests.yml` instead of `integration.yml`.

#### Proposed

The proposed feature is two-fold:
1. Rename the workflow file from `integration-tests.yml` to `integration.yml`
2. Standardize the workflow definitions so that [`dbt-postgres`](https://github.com/dbt-labs/dbt-postgres/blob/a47617d58ea1f87a9ac763690de81ef97608f378/.github/workflows/integration-tests.yml) and [`dbt-redshift`](https://github.com/dbt-labs/dbt-redshift/blob/a145bc15a1db83241442b1d6a19924cdbac2577d/.github/workflows/integration.yml) so they only differ where they need to (e.g., environment variables, etc.).

### Who will this benefit?

People testing a PR in `dbt-adapters` against each of the adapter repos maintained by dbt Labs, like here: https://github.com/dbt-labs/dbt-adapters/pull/372#issuecomment-2536406292

**Comment by mikealfare** [comment] 2024-12-17 19:07
The standardization will effectively happen when we merge all of this into the monorepo. The workflow to run integration tests will probably be `_integration-tests.yml`, though this isn't expected to be run directly. It will get called by other workflows, such as `pull-request-checks.yml` and `publish.yml`. If there is another use case that we need to support, we can add another implementation workflow specific to that use case in the `dbt-adapters` repo. Let me know if the standardization aspect was the main goal, or if there is something beyond that which we would miss. In the meantime, I'd rather close this as a duplicate of a subset of the monorepo work.

**Closed by mikealfare** 2024-12-17 19:07 UTC
Labels: enhancement, tech_debt
